### ISSUE TITLE
Fehlerhafter Link zur Doku

### ISSUE THREAD

**Issue by twern** [xtreme-themes/xtreme-one#3]
Ruft man im Backend den Link zur Dokumentation (https://github.com/xtreme-themes/xtreme-one/xt/wiki/Xtreme-One-Dokumentation ) auf, bekommt man eine 404 Meldung.

Fehler in der Sprachdatei: https://github.com/xtreme-themes/xtreme-one/blob/master/languages/de_DE.po#L4531-L4533

**Comment by nullbytes** [comment]
Vielen Dank für den Hinweis. Der Link wurde geändert und dieses Issues auf den Milestone 1.7.1 gelegt.
